### Recuperar todas las películas
GET http://localhost:1234/movies

### Recuperar una película por id
GET http://localhost:1234/movies/48990183-6c94-11f0-aecd-1c3947369626

### Recuperar todas las películas por un género
GET http://localhost:1234/movies?genre=ACTION

### Crear una película con POST
POST http://localhost:1234/movies
Content-Type: application/json

{
  "id": "7e3fd5ab-60ff-4ae2-92b6-9597f0308d1",
  "title": "Gladiator",
  "year": 2000,
  "director": "Ridley Scott",
  "duration": 155,
  "poster": "https://img.fruugo.com/product/0/60/14417600_max.jpg",
  "genre": ["Action", "Adventure", "Drama"],
  "rate": 8.5
}
### Borrar una película
DELETE http://localhost:1234/movies/30ea3da2-6cdb-11f0-8f77-1c3947369626

### Actualizar una película
PATCH http://localhost:1234/movies/7b5b39be-6d56-11f0-9479-1c3947369626
Content-Type: application/json

{
  "year": 2000
}